Validate forms
- Implement restrictions in forms
- Rename Item class to avoid compiler error CS0542
- Avoid inserting empty item to supply (causes exception due to null casting)
- Fix messages
- Other minor changes